### ISSUE TITLE
Smokestack graphs always showing 0 / 0 for loss and count

### ISSUE THREAD

**Issue by vegu** [20c/graphsrv#13]
Originally reported in https://github.com/20c/vaping/issues/13

**Comment by aspiers** [comment]
Thanks a lot but I just upgraded to 1.1.1 and after `iptables -I OUTPUT --destination $host_in_vaping_config -j DROP`, even though the graph correctly stops plotting for that host, the loss counter for that host either stays at `0` or briefly goes to `1` and then reverts back to `0`.  My config includes:

```yaml
plugins:
  - name: std_fping
    type: fping
    count: 10
    interval: 3s
    output:
      - vodka
```
So if the `iptables` rule is blocking outgoing ICMP traffic for more than 30 seconds then surely the loss counter should go up to 10 at least?

**Comment by vegu** [comment]
does it still show 0/0 or does it show 0/10 ?

If it shows 0/0 can you try forcing a cache refresh in your browser (ctrl+shift+r in chrome for examples)

**Comment by aspiers** [comment]
It shows 0/10 and then sometimes momentarily 1/10 during the outage.

**Comment by aspiers** [comment]
Actually not momentarily, it stays at 1/10 until I delete the rule and then it goes back to 0/10.

**Comment by vegu** [comment]
I see, that sounds like it might actually be broken in more than one place then, i will look into it and make a ticket for it once i  reproduce and narrow down the component causing the issue.

To clarify, the issue i fixed here was an UI issue where the reported packet loss number in the case of partial packet-loss (eg. anything < 100%) would show up as 0.

**Comment by vegu** [comment]
Managed to reproduce it and opened a ticket for it at #14, hope to have it fixed soon :) thanks for the continued reporting on the issue.

**Comment by aspiers** [comment]
You're very welcome - thanks a LOT for the incredibly quick responses! :-)

**Comment by vegu** [comment]
I pushed a fix for this to github, could you do me a favor and install from there and see if this fixes your issue, if it does i'll do another pip release over the weekend.

`pip uninstall graphsrv -y; pip install git+git://github.com/20c/graphsrv.git`

again it will be a javascript issue, so a cache refresh in the browser may be required to see the effect.

thanks

**Comment by aspiers** [comment]
Hmm, after installing from git and forcing cache refresh I still see it stuck at 1/10 during the outage.

**Comment by vegu** [comment]
Hm, is it still showing NaNms as well ? If it is then its definitely not loading the updated javascript.

Could try running it in a chrome incognito window to make sure its not a cache issue (if you run chrome that is).

**Comment by aspiers** [comment]
I found the problem - I was using the wrong version of `pip`!  So it was installing the git version into `/usr/lib64/python3.4/site-packages` instead of `/usr/lib/python2.7/site-packages`.  When I re-ran the above commands using `pip2.7` it started working perfectly :-)  Sorry for the false alarm!

**Comment by vegu** [comment]
No worries, glad to see improvement on the issue at last, ill do a proper release to pip in a while.

**Comment by aspiers** [comment]
Great, thanks!  This really is an awesome tool, and I am telling all my colleagues about it too.  I used to love smokeping except for the fact it was written in Perl, so everything about vaping (including the clever name) is nirvana :-)  I hope the feature suggestions I just made are useful, but feel free to tell me if I'm talking nonsense at any point ;-)
